start_url = "ipc:///tmp/zilean_backtest.ipc"
tick_url = "ipc:///tmp/zilean_backtest/"
use_trade = false
debug = false

[database]
host = "http://localhost"
port = 8123
username = "default"
password = "RyQplVJetI2M"

