start_url = "ipc:///tmp/zilean_backtest_dev.ipc"
tick_url = "ipc:///tmp/zilean_backtest/"
debug = false

[database]
host = "http://localhost"
port = 8123
database = "binance"
username = "default"
password = "RyQplVJetI2M"

